# Generated by Django 5.1.6 on 2025-05-23 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('testScore', models.FloatField()),
                ('age', models.IntegerField(null=True)),
                ('address', models.CharField(choices=[('l', 'Lucknow'), ('p', 'Prayagraj'), ('k', 'Kanpur')], max_length=30, null=True)),
                ('weight', models.FloatField(null=True)),
            ],
        ),
    ]
